jobs:
  - deployment: 'core'
    displayName: "${{ format ('Deploy {0} stage',  'Primary') }}"
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-latest'
    environment: "Primary"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: pwsh
              inputs:
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)\helpers\New-Variables.1