jobs:
  - deployment: 'core'
    displayName: "${{ format ('Deploy {0} stage',  'Primary') }}"
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-latest'
    environment: "Primary"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: PowerShell@2
              inputs:
                targetType: 'filePath'
                filePath: $(System.DefaultWorkingDirectory)/helpers/New-Variables.ps1
                pwsh: true
              displayName: "Export Random Variables"
              name: exportRandomVariables