jobs:
  - deployment: 'core'
    displayName: "${{ format ('Deploy {0} stage',  'Secondary') }}"
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-latest'
    environment: "Secondary"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self