jobs:
  - deployment: 'core'
    displayName: "${{ format ('Deploy {0} stage',  'Secondary') }}"
    pool:
      name: Default
      demands:
        - Agent.OS -equals Linux
    environment: "Secondary"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self